### ISSUE TITLE
Validate yaml file

### ISSUE THREAD

**Issue by gianluca-sabena** [unicredit/sbt-swagger-codegen#8]
Validate yaml file and display meaningful messages.

If run codgen with invalid yaml file (missing required name filed in parameter section):

```
      parameters:
        - in: body
          schema:
            $ref: '#/definitions/authReq'
```

I get a null pointer exception

```
java.lang.NullPointerException
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:713)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:706)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at treehugger.TreePrinters$TreePrinter.print(TreePrinters.scala:706)
        at treehugger.TreePrinters$TreePrinter.printTree(TreePrinters.scala:584)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:709)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:706)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at treehugger.TreePrinters$TreePrinter.print(TreePrinters.scala:706)
        at treehugger.TreePrinters$TreePrinter.printTree(TreePrinters.scala:332)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:709)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:706)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at treehugger.TreePrinters$TreePrinter.print(TreePrinters.scala:706)
        at treehugger.TreePrinters$TreePrinter$$anonfun$printColumn$2.apply(TreePrinters.scala:68)
        at treehugger.TreePrinters$TreePrinter$$anonfun$printColumn$2.apply(TreePrinters.scala:68)
        at treehugger.TreePrinters$TreePrinter.printSeq(TreePrinters.scala:62)
        at treehugger.TreePrinters$TreePrinter.printColumn(TreePrinters.scala:68)
        at treehugger.TreePrinters$TreePrinter.printTree(TreePrinters.scala:461)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:709)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:706)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at treehugger.TreePrinters$TreePrinter.print(TreePrinters.scala:706)
        at treehugger.TreePrinters$TreePrinter.printTree(TreePrinters.scala:576)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:709)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:706)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at treehugger.TreePrinters$TreePrinter.print(TreePrinters.scala:706)
        at treehugger.TreePrinters$TreePrinter.printTree(TreePrinters.scala:541)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:709)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:706)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at treehugger.TreePrinters$TreePrinter.print(TreePrinters.scala:706)
        at treehugger.TreePrinters$TreePrinter.printTree(TreePrinters.scala:388)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:709)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:706)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at treehugger.TreePrinters$TreePrinter.print(TreePrinters.scala:706)
        at treehugger.TreePrinters$TreePrinter$$anonfun$printRow$2.apply(TreePrinters.scala:72)
        at treehugger.TreePrinters$TreePrinter$$anonfun$printRow$2.apply(TreePrinters.scala:72)
        at treehugger.TreePrinters$TreePrinter.printSeq(TreePrinters.scala:61)
        at treehugger.TreePrinters$TreePrinter.printRow(TreePrinters.scala:72)
        at treehugger.TreePrinters$TreePrinter.printTree(TreePrinters.scala:544)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:709)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:706)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at treehugger.TreePrinters$TreePrinter.print(TreePrinters.scala:706)
        at treehugger.TreePrinters$TreePrinter$$anonfun$printColumn$2.apply(TreePrinters.scala:68)
        at treehugger.TreePrinters$TreePrinter$$anonfun$printColumn$2.apply(TreePrinters.scala:68)
        at treehugger.TreePrinters$TreePrinter.printSeq(TreePrinters.scala:61)
        at treehugger.TreePrinters$TreePrinter.printColumn(TreePrinters.scala:68)
        at treehugger.TreePrinters$TreePrinter.printTree(TreePrinters.scala:461)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:709)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:706)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at treehugger.TreePrinters$TreePrinter.print(TreePrinters.scala:706)
        at treehugger.TreePrinters$TreePrinter.printTree(TreePrinters.scala:368)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:709)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:706)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at treehugger.TreePrinters$TreePrinter.print(TreePrinters.scala:706)
        at treehugger.TreePrinters$TreePrinter$$anonfun$printColumn$2.apply(TreePrinters.scala:68)
        at treehugger.TreePrinters$TreePrinter$$anonfun$printColumn$2.apply(TreePrinters.scala:68)
        at treehugger.TreePrinters$TreePrinter.printSeq(TreePrinters.scala:61)
        at treehugger.TreePrinters$TreePrinter.printColumn(TreePrinters.scala:68)
        at treehugger.TreePrinters$TreePrinter.printTree(TreePrinters.scala:456)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:709)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:706)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at treehugger.TreePrinters$TreePrinter.print(TreePrinters.scala:706)
        at treehugger.TreePrinters$TreePrinter.printTree(TreePrinters.scala:322)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:709)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:706)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at treehugger.TreePrinters$TreePrinter.print(TreePrinters.scala:706)
        at treehugger.TreePrinters$TreePrinter$$anonfun$printTree$2.apply(TreePrinters.scala:311)
        at treehugger.TreePrinters$TreePrinter$$anonfun$printTree$2.apply(TreePrinters.scala:311)
        at treehugger.TreePrinters$TreePrinter.printSeq(TreePrinters.scala:61)
        at treehugger.TreePrinters$TreePrinter.printSeq(TreePrinters.scala:62)
        at treehugger.TreePrinters$TreePrinter.printSeq(TreePrinters.scala:62)
        at treehugger.TreePrinters$TreePrinter.printSeq(TreePrinters.scala:62)
        at treehugger.TreePrinters$TreePrinter.printSeq(TreePrinters.scala:62)
        at treehugger.TreePrinters$TreePrinter.printSeq(TreePrinters.scala:62)
        at treehugger.TreePrinters$TreePrinter.printSeq(TreePrinters.scala:62)
        at treehugger.TreePrinters$TreePrinter.printSeq(TreePrinters.scala:62)
        at treehugger.TreePrinters$TreePrinter.printTree(TreePrinters.scala:311)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:709)
        at treehugger.TreePrinters$TreePrinter$$anonfun$print$1.apply(TreePrinters.scala:706)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at treehugger.TreePrinters$TreePrinter.print(TreePrinters.scala:706)
        at treehugger.TreePrinters$class.treeToString(TreePrinters.scala:731)
        at treehugger.Forest.treeToString(Forest.scala:3)
        at eu.unicredit.swagger.CodeGen$.generatePlayServerStub(CodeGen.scala:219)
        at eu.unicredit.swagger.SwaggerCodegenPlugin$$anonfun$45.apply(SwaggerCodegenPlugin.scala:327)
        at eu.unicredit.swagger.SwaggerCodegenPlugin$$anonfun$45.apply(SwaggerCodegenPlugin.scala:322)
        at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:722)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:721)
        at eu.unicredit.swagger.SwaggerCodegenPlugin$.swaggerPlayServerCodeGenImpl(SwaggerCodegenPlugin.scala:322)
        at eu.unicredit.swagger.SwaggerCodegenPlugin$$anonfun$swaggerPlayServerCodeGenCommand$1.apply(SwaggerCodegenPlugin.scala:293)
        at eu.unicredit.swagger.SwaggerCodegenPlugin$$anonfun$swaggerPlayServerCodeGenCommand$1.apply(SwaggerCodegenPlugin.scala:269)
        at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
        at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
        at sbt.Command$.process(Command.scala:92)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:98)
        at sbt.MainLoop$.run(MainLoop.scala:91)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
        at sbt.MainLoop$.runLogged(MainLoop.scala:24)
        at sbt.StandardMain$.runManaged(Main.scala:53)
        at sbt.xMain.run(Main.scala:28)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)

```

**Comment by nicolaemarasoiu** [comment]
Hi guys do you have any idea what might cause this? are you using Avro hugger?

**Comment by mfirry** [comment]
Hi, not using `avrohugger` (this project has nothing to do with `avro` but we **used to use** [treehugger](https://github.com/eed3si9n/treehugger) but everything was moved to `scalameta` (actually we should consider this issue invalid). @fralken what do you think?
